namespace Chatter.Rest.Hal.CodeGenerators;

/// <summary>
/// The marker attribute the generator looks for, emitted into every compilation the generator runs
/// in. Shipping it from the generator itself means installing the CodeGenerators package is enough
/// to make <c>[HalResponse]</c> available; without it the attribute has to come from somewhere else
/// and the generator never fires.
/// </summary>
internal static class AttributeSource
{
	internal const string HintName = "HalResponseAttribute.g.cs";

	internal const string Source = @"// <auto-generated />

#nullable enable

namespace Chatter.Rest.Hal
{
    /// <summary>
    /// Marks a partial class for HAL source generation. The generator adds the reserved
    /// <c>_links</c> and <c>_embedded</c> members to the annotated type.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class HalResponseAttribute : global::System.Attribute
    {
    }
}
";
}
