using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Chatter.Rest.Hal.CodeGenerators;

internal class Emitter
{
	private const string Indentation = "    ";

	internal static void Emit(SourceProductionContext context,
		ImmutableArray<HalClassInfo> halResponseClasses)
	{
		if (halResponseClasses.IsDefaultOrEmpty)
		{
			return;
		}

		// Seed the reserved marker hint: a valid global-namespace target named HalResponseAttribute
		// would otherwise sanitize onto the post-initialization attribute's hint name and make
		// AddSource throw instead of generating the target.
		var hintNames = new HashSet<string>(StringComparer.Ordinal) { "HalResponseAttribute" };
		foreach (var entry in halResponseClasses)
		{
			context.AddSource(HintNameFor(entry.MetadataName, hintNames), GenerateCode(entry));
		}
	}

	/// <summary>
	/// Turns a metadata name into a unique, file-name-safe hint. Arity backticks and the nested-type
	/// separator are not valid in a hint name, and two distinct metadata names can sanitize onto the
	/// same text, so collisions get a numeric suffix.
	/// </summary>
	private static string HintNameFor(string metadataName, HashSet<string> taken)
	{
		var sanitized = metadataName.Replace('+', '.').Replace('`', '_');
		var candidate = sanitized;
		var suffix = 1;
		while (!taken.Add(candidate))
		{
			candidate = $"{sanitized}_{suffix++}";
		}

		return $"{candidate}.g.cs";
	}

	private static string GenerateCode(in HalClassInfo info)
	{
		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated />");
		sb.AppendLine();
		sb.AppendLine("#nullable enable");
		sb.AppendLine();

		var depth = 0;
		var hasNamespace = !string.IsNullOrEmpty(info.Namespace);
		if (hasNamespace)
		{
			sb.AppendLine($"namespace {info.Namespace}");
			sb.AppendLine("{");
			depth++;
		}

		foreach (var containingType in info.ContainingTypes)
		{
			// Keyword carries any required modifiers plus "partial" (e.g. "readonly partial struct").
			sb.AppendLine($"{Indent(depth)}{containingType.Keyword} {containingType.NameWithTypeParameters}");
			sb.AppendLine($"{Indent(depth)}{{");
			depth++;
		}

		sb.AppendLine($"{Indent(depth)}partial class {info.NameWithTypeParameters}");
		sb.AppendLine($"{Indent(depth)}{{");
		depth++;
		sb.AppendLine($"{Indent(depth)}[global::System.Text.Json.Serialization.JsonPropertyName(\"_links\")]");
		sb.AppendLine($"{Indent(depth)}public global::Chatter.Rest.Hal.LinkCollection? Links {{ get; set; }}");
		sb.AppendLine();
		sb.AppendLine($"{Indent(depth)}[global::System.Text.Json.Serialization.JsonPropertyName(\"_embedded\")]");
		sb.AppendLine($"{Indent(depth)}public global::Chatter.Rest.Hal.EmbeddedResourceCollection? Embedded {{ get; set; }}");
		depth--;
		sb.AppendLine($"{Indent(depth)}}}");

		for (var i = 0; i < info.ContainingTypes.Length; i++)
		{
			depth--;
			sb.AppendLine($"{Indent(depth)}}}");
		}

		if (hasNamespace)
		{
			sb.AppendLine("}");
		}

		return sb.ToString();
	}

	private static string Indent(int depth) =>
		depth <= 0 ? string.Empty : string.Concat(Enumerable.Repeat(Indentation, depth));
}
