using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Chatter.Rest.Hal.CodeGenerators;

internal readonly struct HalClassInfo : IEquatable<HalClassInfo>
{
	internal string Name { get; }
	internal string? Namespace { get; }

	internal HalClassInfo(string name, string? ns)
	{
		Name = name;
		Namespace = ns;
	}

	public bool Equals(HalClassInfo other) =>
		Name == other.Name && Namespace == other.Namespace;

	public override bool Equals(object? obj) =>
		obj is HalClassInfo other && Equals(other);

	public override int GetHashCode()
	{
		unchecked
		{
			return (Name.GetHashCode() * 397) ^ (Namespace?.GetHashCode() ?? 0);
		}
	}
}

internal class Emitter
{
	internal static void Emit(SourceProductionContext context,
		ImmutableArray<HalClassInfo> halResponseClasses)
	{
		if (halResponseClasses.IsDefaultOrEmpty)
		{
			return;
		}

		foreach (var entry in halResponseClasses)
		{
			AddSource(context, entry.Name, string.IsNullOrEmpty(entry.Namespace) ? null : entry.Namespace);
		}
	}

	private static void AddSource(SourceProductionContext context, string name, string? ns)
	{
		var code = GenerateCode(name, ns);
		var typeNamespace = ns is null ? string.Empty : $"{ns}.";
		context.AddSource($"{typeNamespace}{name}.g.cs", code);
	}

    private static string GenerateCode(string name, string? ns)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using Chatter.Rest.Hal;");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    partial class {name}");
        sb.AppendLine("    {");
        sb.AppendLine("        [JsonPropertyName(\"_links\")] ");
        sb.AppendLine("        public LinkCollection? Links { get; set; }");
        sb.AppendLine();
        sb.AppendLine("        [JsonPropertyName(\"_embedded\")] ");
        sb.AppendLine("        public EmbeddedResourceCollection? Embedded { get; set; }");
        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine("}");
        }
        return sb.ToString();
    }

	internal static string? GetNamespaceFrom(SyntaxNode s) =>
		s.Parent switch
		{
			FileScopedNamespaceDeclarationSyntax fileScopedNamespace => fileScopedNamespace.Name.ToString(),
			NamespaceDeclarationSyntax namespaceDeclarationSyntax => namespaceDeclarationSyntax.Name.ToString(),
			null => null,
			_ => GetNamespaceFrom(s.Parent)
		};
}
