name: Hal CI/CD

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual build from GitHub UI'

  push:
    branches:
      - 'feature/**'
    paths:
      - '**/src/Chatter.Rest.Hal/**'
      - '.github/workflows/hal-cicd.yml'
      - '**/test/Chatter.Rest.Hal.Tests/**'

  pull_request:
    branches:
      - main
    paths:
      - '**/src/Chatter.Rest.Hal/**'
      - '.github/workflows/hal-cicd.yml'
      - '**/test/Chatter.Rest.Hal.Tests/**'

env:
  dotnet-version: '8.0.x'

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.dotnet-version }}
          cache: true
          cache-dependency-path: |
            **/packages.lock.json

      - name: Restore
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test '/home/runner/work/Chatter.Rest.Hal/Chatter.Rest.Hal/test/Chatter.Rest.Hal.Tests/Chatter.Rest.Hal.Tests.csproj' -c Release --no-build

      - name: Pack
        run: dotnet pack '/home/runner/work/Chatter.Rest.Hal/Chatter.Rest.Hal/src/Chatter.Rest.Hal/Chatter.Rest.Hal.csproj' -c Release --no-build -o publish/nuget

      - name: Upload NuGet
        uses: actions/upload-artifact@v6
        with:
          name: nuget
          path: /home/runner/work/Chatter.Rest.Hal/Chatter.Rest.Hal/publish/nuget/**
          retention-days: 5
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true

    environment:
      name: Production

    env:
      NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY_CHATTER_HAL }}
      NUGET_URL: https://api.nuget.org/v3/index.json

    permissions:
      contents: read

    steps:
      - name: Download NuGet
        uses: actions/download-artifact@v6
        with:
          name: nuget
          path: ./dist/nuget

      - name: Push NuGet packages
        shell: bash
        run: |
          dotnet nuget push "./dist/nuget/*.nupkg" \
            -k '${{ env.NUGET_AUTH_TOKEN }}' \
            -s '${{ env.NUGET_URL }}' \
            --skip-duplicate